version: "3"

services:
  client:        
    build:
      context: ./client/ 
    restart: always        
    ports:            
      - "3000:3000"   
    working_dir: /client/src/app     
    volumes:            
      - ./client:/client/src/app            
    depends_on:
      - api   
    command: npm start
  api:        
    build:
      context: ./api/
    command: npm start  
    restart: always        
    ports:            
      - "9000:9000"        
    volumes:            
      - ./api:/api            
      - /api/node_modules        
    depends_on:            
      - mongodb
    links: 
      - mongodb 
  mongodb:        
    image: 'mongo'
    restart: always       
    container_name: 'mongodb'
    ports:            
      - '27017:27017'
